spring:
  application:
    name: composite

eureka:
  instance:
    metadata-map: 
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    eureka-server-port: 8761
    register-with-server: true
    


atomic.service.url: http://atomic/sayHello

server:
  port: 0
  
atomic:
  ribbon:
    DeploymentContextBasedVipAddresses: atomic
    ReadTimeout: 5000
    MaxAutoRetries: 2
